/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Available_Busses;

import AfterLogInPage.SearchResult;
import ComfirmPage.ConfirmYourTicket;

import java.awt.*;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;

/**
 * @author Tashin Parvez
 */
public class Hanif extends javax.swing.JFrame {

    /**
     * Creates new form Hanif
     */
    public Hanif() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        a1 = new javax.swing.JButton();
        a2 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        c1 = new javax.swing.JButton();
        c2 = new javax.swing.JButton();
        d1 = new javax.swing.JButton();
        d2 = new javax.swing.JButton();
        h2 = new javax.swing.JButton();
        g2 = new javax.swing.JButton();
        f2 = new javax.swing.JButton();
        e2 = new javax.swing.JButton();
        e1 = new javax.swing.JButton();
        f1 = new javax.swing.JButton();
        g1 = new javax.swing.JButton();
        h1 = new javax.swing.JButton();
        i2 = new javax.swing.JButton();
        i1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        a3 = new javax.swing.JButton();
        a4 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        c3 = new javax.swing.JButton();
        c4 = new javax.swing.JButton();
        d3 = new javax.swing.JButton();
        d4 = new javax.swing.JButton();
        h4 = new javax.swing.JButton();
        g4 = new javax.swing.JButton();
        f4 = new javax.swing.JButton();
        e4 = new javax.swing.JButton();
        e3 = new javax.swing.JButton();
        f3 = new javax.swing.JButton();
        g3 = new javax.swing.JButton();
        h3 = new javax.swing.JButton();
        i4 = new javax.swing.JButton();
        i3 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        applicationName1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        showCoachName = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        backToPrevious = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Entrance");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 207, -1, 77));

        jLabel3.setText("Driver");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 26, 70, 44));

        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Engine");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addContainerGap(28, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))
        );
        jPanel8Layout.setVerticalGroup(
                jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addContainerGap(15, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17))
        );

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 100, 70));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 9, -1, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 531, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 18, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 136, 531, -1));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        a1.setText("A 1");
        a1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a1ActionPerformed(evt);
            }
        });
        jPanel5.add(a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 74, 53, 50));

        a2.setText("A 2");
        a2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a2ActionPerformed(evt);
            }
        });
        jPanel5.add(a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 53, 50));

        b1.setText("B 1");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel5.add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 74, 53, 50));

        b2.setText("B 2");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        jPanel5.add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 0, 53, 50));

        c1.setText("C 1");
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        jPanel5.add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 74, 53, 50));

        c2.setText("C 3");
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });
        jPanel5.add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 0, 53, 50));

        d1.setText("D 1");
        d1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d1ActionPerformed(evt);
            }
        });
        jPanel5.add(d1, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 74, 53, 50));

        d2.setText("D 2");
        d2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d2ActionPerformed(evt);
            }
        });
        jPanel5.add(d2, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 0, 53, 50));

        h2.setText("H 2");
        h2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h2ActionPerformed(evt);
            }
        });
        jPanel5.add(h2, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 0, 53, 50));

        g2.setText("G 2");
        g2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g2ActionPerformed(evt);
            }
        });
        jPanel5.add(g2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 53, 50));

        f2.setText("F 2");
        f2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f2ActionPerformed(evt);
            }
        });
        jPanel5.add(f2, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 0, 53, 50));

        e2.setText("E 2");
        e2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e2ActionPerformed(evt);
            }
        });
        jPanel5.add(e2, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 0, 53, 50));

        e1.setText("E 1");
        e1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e1ActionPerformed(evt);
            }
        });
        jPanel5.add(e1, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 74, 53, 50));

        f1.setText("F 1");
        f1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f1ActionPerformed(evt);
            }
        });
        jPanel5.add(f1, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 74, 53, 50));

        g1.setText("G 1");
        g1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g1ActionPerformed(evt);
            }
        });
        jPanel5.add(g1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 74, 53, 50));

        h1.setText("H 1");
        h1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h1ActionPerformed(evt);
            }
        });
        jPanel5.add(h1, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 74, 53, 50));

        i2.setText("I 2");
        i2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i2ActionPerformed(evt);
            }
        });
        jPanel5.add(i2, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 0, 53, 50));

        i1.setText("I 1");
        i1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i1ActionPerformed(evt);
            }
        });
        jPanel5.add(i1, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 74, 53, 50));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, -1, -1));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        a3.setText("A 3");
        a3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a3ActionPerformed(evt);
            }
        });
        jPanel6.add(a3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 74, 53, 50));

        a4.setText("A 4");
        a4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a4ActionPerformed(evt);
            }
        });
        jPanel6.add(a4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 53, 50));

        b3.setText("B 3");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        jPanel6.add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 74, 53, 50));

        b4.setText("B 4");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        jPanel6.add(b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 0, 53, 50));

        c3.setText("C 3");
        c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3ActionPerformed(evt);
            }
        });
        jPanel6.add(c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 74, 53, 50));

        c4.setText("C 4");
        c4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c4ActionPerformed(evt);
            }
        });
        jPanel6.add(c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 0, 53, 50));

        d3.setText("D 3");
        d3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d3ActionPerformed(evt);
            }
        });
        jPanel6.add(d3, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 74, 53, 50));

        d4.setText("D 4");
        d4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d4ActionPerformed(evt);
            }
        });
        jPanel6.add(d4, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 0, 53, 50));

        h4.setText("H 4");
        h4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h4ActionPerformed(evt);
            }
        });
        jPanel6.add(h4, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 0, 53, 50));

        g4.setText("G 4");
        g4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g4ActionPerformed(evt);
            }
        });
        jPanel6.add(g4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 53, 50));

        f4.setText("F 4");
        f4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f4ActionPerformed(evt);
            }
        });
        jPanel6.add(f4, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 0, 53, 50));

        e4.setText("E 4");
        e4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e4ActionPerformed(evt);
            }
        });
        jPanel6.add(e4, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 0, 53, 50));

        e3.setText("E 3");
        e3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                e3ActionPerformed(evt);
            }
        });
        jPanel6.add(e3, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 74, 53, 50));

        f3.setText("F 3");
        f3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f3ActionPerformed(evt);
            }
        });
        jPanel6.add(f3, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 74, 53, 50));

        g3.setText("G 3");
        g3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g3ActionPerformed(evt);
            }
        });
        jPanel6.add(g3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 74, 53, 50));

        h3.setText("H 3");
        h3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h3ActionPerformed(evt);
            }
        });
        jPanel6.add(h3, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 74, 53, 50));

        i4.setText("I 4");
        i4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i4ActionPerformed(evt);
            }
        });
        jPanel6.add(i4, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 0, 53, 50));

        i3.setText("I 3");
        i3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                i3ActionPerformed(evt);
            }
        });
        jPanel6.add(i3, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 74, 53, 50));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 9, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 690, 310));

        applicationName1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        applicationName1.setText("JABO");

        jLabel4.setText("Choose Your Comfort");

        jLabel6.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        jLabel6.setText("HANIF PARIBAHAN");

        showCoachName.setText("AC Coach");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("* Choose seats of your choice");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(applicationName1))
                                        .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(showCoachName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 435, Short.MAX_VALUE)
                                                .addComponent(jLabel4))
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(applicationName1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(showCoachName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addGap(14, 14, 14))
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 6, -1, -1));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 510, 43, -1));

        jLabel12.setText("[NB: Red colored seats are pre-booked]");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 486, 280, -1));

        backToPrevious.setText("Go Back To Previous Page");
        backToPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToPreviousActionPerformed(evt);
            }
        });
        getContentPane().add(backToPrevious, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 470, 190, 30));

        nextButton.setText("NEXT");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });
        getContentPane().add(nextButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 470, 130, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    ArrayList<String> countingSeats = new ArrayList<>();

//    int totalSelectedSeats = countingSeats.size();


    //-------------------------- Button action listeners__________________________________
    private void a1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a1ActionPerformed
        // TODO add your handling code here:

        String str = String.valueOf(a1.getBackground());
        if (str.equals("java.awt.Color[r=255,g=0,b=0]")) {
        } else if (str.equals("java.awt.Color[r=255,g=255,b=0]")) {
            a1.setBackground(Color.WHITE);
            countingSeats.remove(a1.getText()); // removing that string
        } else {
            a1.setBackground(Color.YELLOW);
            countingSeats.add(a1.getText()); // adding that string
        }
//        countingSeats.remove(a1.getName()); // removing that string
//        countingSeats.add(a1.getName()); // adding that string

    }//GEN-LAST:event_a1ActionPerformed

    private void a2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a2ActionPerformed
        // TODO add your handling code here:

        String str = String.valueOf(a2.getBackground());
        if (str.equals("java.awt.Color[r=255,g=0,b=0]")) {
        } else if (str.equals("java.awt.Color[r=255,g=255,b=0]")) {
            a2.setBackground(Color.WHITE);
            countingSeats.remove(a2.getText()); // removing that string
//        countingSeats.add(a1.getName()); // adding that string
        } else {
            a2.setBackground(Color.YELLOW);
            //        countingSeats.remove(a1.getName()); // removing that string
            countingSeats.add(a2.getText()); // adding that string
        }

    }//GEN-LAST:event_a2ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:

        String str = String.valueOf(b1.getBackground());
        if (str.equals("java.awt.Color[r=255,g=0,b=0]")) {
        } else if (str.equals("java.awt.Color[r=255,g=255,b=0]")) {
            b1.setBackground(Color.WHITE);
            countingSeats.remove(b1.getText()); // removing that string
//        countingSeats.add(a1.getName()); // adding that string
        } else {
            b1.setBackground(Color.YELLOW);
            //        countingSeats.remove(a1.getName()); // removing that string
            countingSeats.add(b1.getText()); // adding that string
        }

    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:

        String str = String.valueOf(b2.getBackground());
        if (str.equals("java.awt.Color[r=255,g=0,b=0]")) {
        } else if (str.equals("java.awt.Color[r=255,g=255,b=0]")) {
            b2.setBackground(Color.WHITE);
            countingSeats.remove(b2.getText()); // removing that string
//        countingSeats.add(a1.getName()); // adding that string
        } else {
            b2.setBackground(Color.YELLOW);
            countingSeats.add(b2.getText()); // adding that string
        }

    }//GEN-LAST:event_b2ActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:

        String str = String.valueOf(c1.getBackground());
        if (str.equals("java.awt.Color[r=255,g=0,b=0]")) {
        } else if (str.equals("java.awt.Color[r=255,g=255,b=0]")) {
            c1.setBackground(Color.WHITE);
            countingSeats.remove(c1.getText()); // removing that string
//        countingSeats.add(a1.getName()); // adding that string
        } else {
            c1.setBackground(Color.YELLOW);
            //        countingSeats.remove(c1.getName()); // removing that string
            countingSeats.add(c1.getText()); // adding that string
        }

    }//GEN-LAST:event_c1ActionPerformed


    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
        // TODO add your handling code here:

        String str = String.valueOf(c2.getBackground());
        if (str.equals("java.awt.Color[r=255,g=0,b=0]")) {
        } else if (str.equals("java.awt.Color[r=255,g=255,b=0]")) {
            c2.setBackground(Color.WHITE);
            countingSeats.remove(c2.getText()); // removing that string
//        countingSeats.add(a1.getName()); // adding that string
        } else {
            c2.setBackground(Color.YELLOW);
            //        countingSeats.remove(a1.getName()); // removing that string
            countingSeats.add(c2.getText()); // adding that string
        }

    }//GEN-LAST:event_c2ActionPerformed

    private void d1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d1ActionPerformed
        // TODO add your handling code here:

        String str = String.valueOf(d1.getBackground());
        if (str.equals("java.awt.Color[r=255,g=0,b=0]")) {
        } else if (str.equals("java.awt.Color[r=255,g=255,b=0]")) {
            d1.setBackground(Color.WHITE);
            countingSeats.remove(d1.getText()); // removing that string
//        countingSeats.add(a1.getName()); // adding that string
        } else {
            d1.setBackground(Color.YELLOW);
            //        countingSeats.remove(a1.getName()); // removing that string
            countingSeats.add(d1.getText()); // adding that string
        }


    }//GEN-LAST:event_d1ActionPerformed

    private void d2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d2ActionPerformed
        // TODO add your handling code here:

        String str = String.valueOf(d2.getBackground());
        if (str.equals("java.awt.Color[r=255,g=0,b=0]")) {
        } else if (str.equals("java.awt.Color[r=255,g=255,b=0]")) {
            d2.setBackground(Color.WHITE);
            countingSeats.remove(d2.getText()); // removing that string
//        countingSeats.add(a1.getName()); // adding that string
        } else {
            d2.setBackground(Color.YELLOW);
            //        countingSeats.remove(a1.getName()); // removing that string
            countingSeats.add(d2.getText()); // adding that string
        }

    }//GEN-LAST:event_d2ActionPerformed

    private void h2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h2ActionPerformed
        // TODO add your handling code here:

        String str = String.valueOf(h2.getBackground());
        if (str.equals("java.awt.Color[r=255,g=0,b=0]")) {
        } else if (str.equals("java.awt.Color[r=255,g=255,b=0]")) {
            h2.setBackground(Color.WHITE);
            countingSeats.remove(h2.getText()); // removing that string
//        countingSeats.add(a1.getText()); // adding that string
        } else {
            h2.setBackground(Color.YELLOW);
            //        countingSeats.remove(a1.getName()); // removing that string
            countingSeats.add(h2.getText()); // adding that string
        }

    }//GEN-LAST:event_h2ActionPerformed

    private void g2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g2ActionPerformed
        // TODO add your handling code here:

        String str = String.valueOf(g2.getBackground());
        if (str.equals("java.awt.Color[r=255,g=0,b=0]")) {
        } else if (str.equals("java.awt.Color[r=255,g=255,b=0]")) {
            g2.setBackground(Color.WHITE);
            countingSeats.remove(g2.getText()); // removing that string
//        countingSeats.add(a1.getName()); // adding that string
        } else {
            g2.setBackground(Color.YELLOW);
            //        countingSeats.remove(a1.getName()); // removing that string
            countingSeats.add(g2.getText()); // adding that string
        }

    }//GEN-LAST:event_g2ActionPerformed

    private void f2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f2ActionPerformed
        // TODO add your handling code here:

        String str = String.valueOf(f2.getBackground());
        if (str.equals("java.awt.Color[r=255,g=0,b=0]")) {
        } else if (str.equals("java.awt.Color[r=255,g=255,b=0]")) {
            f2.setBackground(Color.WHITE);
            countingSeats.remove(f2.getText()); // removing that string
//        countingSeats.add(a1.getName()); // adding that string
        } else {
            f2.setBackground(Color.YELLOW);
            //        countingSeats.remove(a1.getName()); // removing that string
            countingSeats.add(f2.getText()); // adding that string
        }

    }//GEN-LAST:event_f2ActionPerformed

    private void e2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e2ActionPerformed
        // TODO add your handling code here:

        String str = String.valueOf(e2.getBackground());
        if (str.equals("java.awt.Color[r=255,g=0,b=0]")) {
        } else if (str.equals("java.awt.Color[r=255,g=255,b=0]")) {
            e2.setBackground(Color.WHITE);
            countingSeats.remove(e2.getText()); // removing that string
//        countingSeats.add(a1.getName()); // adding that string
        } else {
            e2.setBackground(Color.YELLOW);
            //        countingSeats.remove(a1.getName()); // removing that string
            countingSeats.add(e2.getText()); // adding that string
        }

    }//GEN-LAST:event_e2ActionPerformed

    private void e1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e1ActionPerformed
        // TODO add your handling code here:

        String str = String.valueOf(e1.getBackground());
        if (str.equals("java.awt.Color[r=255,g=0,b=0]")) {
        } else if (str.equals("java.awt.Color[r=255,g=255,b=0]")) {
            e1.setBackground(Color.WHITE);
            countingSeats.remove(e1.getText()); // removing that string
//        countingSeats.add(a1.getName()); // adding that string
        } else {
            e1.setBackground(Color.YELLOW);
            //        countingSeats.remove(e1.getName()); // removing that string
            countingSeats.add(e1.getText()); // adding that string
        }


    }//GEN-LAST:event_e1ActionPerformed

    private void f1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f1ActionPerformed
        // TODO add your handling code here:

        String str = String.valueOf(f1.getBackground());
        if (str.equals("java.awt.Color[r=255,g=0,b=0]")) {
        } else if (str.equals("java.awt.Color[r=255,g=255,b=0]")) {
            f1.setBackground(Color.WHITE);
            countingSeats.remove(f1.getText()); // removing that string
//        countingSeats.add(a1.getName()); // adding that string
        } else {
            f1.setBackground(Color.YELLOW);
            //        countingSeats.remove(f1.getName()); // removing that string
            countingSeats.add(f1.getText()); // adding that string
        }


    }//GEN-LAST:event_f1ActionPerformed

    private void g1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g1ActionPerformed
        // TODO add your handling code here:

        String str = String.valueOf(g1.getBackground());
        if (str.equals("java.awt.Color[r=255,g=0,b=0]")) {
        } else if (str.equals("java.awt.Color[r=255,g=255,b=0]")) {
            g1.setBackground(Color.WHITE);
            countingSeats.remove(g1.getText()); // removing that string
//        countingSeats.add(a1.getName()); // adding that string
        } else {
            g1.setBackground(Color.YELLOW);
            //        countingSeats.remove(g1.getName()); // removing that string
            countingSeats.add(g1.getText()); // adding that string
        }


    }//GEN-LAST:event_g1ActionPerformed

    private void h1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h1ActionPerformed
        // TODO add your handling code here:

        String str = String.valueOf(h1.getBackground());
        if (str.equals("java.awt.Color[r=255,g=0,b=0]")) {
        } else if (str.equals("java.awt.Color[r=255,g=255,b=0]")) {
            h1.setBackground(Color.WHITE);
            countingSeats.remove(h1.getText()); // removing that string
//        countingSeats.add(a1.getName()); // adding that string
        } else {
            h1.setBackground(Color.YELLOW);
            //        countingSeats.remove(a1.getName()); // removing that string
            countingSeats.add(h1.getText()); // adding that string
        }


    }//GEN-LAST:event_h1ActionPerformed

    private void i2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i2ActionPerformed
        // TODO add your handling code here:

        String str = String.valueOf(i2.getBackground());
        if (str.equals("java.awt.Color[r=255,g=0,b=0]")) {
        } else if (str.equals("java.awt.Color[r=255,g=255,b=0]")) {
            i2.setBackground(Color.WHITE);
            countingSeats.remove(i2.getText()); // removing that string
//        countingSeats.add(a1.getName()); // adding that string
        } else {
            i2.setBackground(Color.YELLOW);
            //        countingSeats.remove(a1.getName()); // removing that string
            countingSeats.add(i2.getText()); // adding that string
        }

    }//GEN-LAST:event_i2ActionPerformed

    private void i1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i1ActionPerformed
        // TODO add your handling code here:

        String str = String.valueOf(i1.getBackground());
        if (str.equals("java.awt.Color[r=255,g=0,b=0]")) {
        } else if (str.equals("java.awt.Color[r=255,g=255,b=0]")) {
            i1.setBackground(Color.WHITE);
            countingSeats.remove(i1.getText()); // removing that string
//        countingSeats.add(a1.getName()); // adding that string
        } else {
            i1.setBackground(Color.YELLOW);
            //        countingSeats.remove(i1.getName()); // removing that string
            countingSeats.add(i1.getText()); // adding that string
        }

    }//GEN-LAST:event_i1ActionPerformed

    //----------------------------- 333333333333333333333333333333333

    private void a3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a3ActionPerformed
        // TODO add your handling code here:

        String str = String.valueOf(a3.getBackground());
        if (str.equals("java.awt.Color[r=255,g=0,b=0]")) {
        } else if (str.equals("java.awt.Color[r=255,g=255,b=0]")) {
            a3.setBackground(Color.WHITE);
            countingSeats.remove(a3.getText()); // removing that string
//        countingSeats.add(a1.getName()); // adding that string
        } else {
            a3.setBackground(Color.YELLOW);
            //        countingSeats.remove(a1.getName()); // removing that string
            countingSeats.add(a3.getText()); // adding that string
        }

    }//GEN-LAST:event_a3ActionPerformed


    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:

        String str = String.valueOf(b3.getBackground());
        if (str.equals("java.awt.Color[r=255,g=0,b=0]")) {
        } else if (str.equals("java.awt.Color[r=255,g=255,b=0]")) {
            b3.setBackground(Color.WHITE);
            countingSeats.remove(b3.getText()); // removing that string
//        countingSeats.add(a1.getName()); // adding that string
        } else {
            b3.setBackground(Color.YELLOW);
            //        countingSeats.remove(a1.getName()); // removing that string
            countingSeats.add(b3.getText()); // adding that string
        }

    }//GEN-LAST:event_b3ActionPerformed

    private void c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3ActionPerformed
        // TODO add your handling code here:

        String str = String.valueOf(c3.getBackground());
        if (str.equals("java.awt.Color[r=255,g=0,b=0]")) {
        } else if (str.equals("java.awt.Color[r=255,g=255,b=0]")) {
            c3.setBackground(Color.WHITE);
            countingSeats.remove(c3.getText()); // removing that string
//        countingSeats.add(a1.getName()); // adding that string
        } else {
            c3.setBackground(Color.YELLOW);
            //        countingSeats.remove(a1.getName()); // removing that string
            countingSeats.add(c3.getText()); // adding that string
        }

    }//GEN-LAST:event_c3ActionPerformed

    private void d3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d3ActionPerformed
        // TODO add your handling code here:

        String str = String.valueOf(d3.getBackground());
        if (str.equals("java.awt.Color[r=255,g=0,b=0]")) {
        } else if (str.equals("java.awt.Color[r=255,g=255,b=0]")) {
            d3.setBackground(Color.WHITE);
            countingSeats.remove(d3.getText()); // removing that string
//        countingSeats.add(a1.getName()); // adding that string
        } else {
            d3.setBackground(Color.YELLOW);
            //        countingSeats.remove(a1.getName()); // removing that string
            countingSeats.add(d3.getText()); // adding that string
        }

    }//GEN-LAST:event_d3ActionPerformed

    private void e3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e3ActionPerformed
        // TODO add your handling code here:

        String str = String.valueOf(e3.getBackground());
        if (str.equals("java.awt.Color[r=255,g=0,b=0]")) {
        } else if (str.equals("java.awt.Color[r=255,g=255,b=0]")) {
            e3.setBackground(Color.WHITE);
            countingSeats.remove(e3.getText()); // removing that string
//        countingSeats.add(a1.getName()); // adding that string
        } else {
            e3.setBackground(Color.YELLOW);
            //        countingSeats.remove(a1.getName()); // removing that string
            countingSeats.add(e3.getText()); // adding that string
        }

    }//GEN-LAST:event_e3ActionPerformed

    private void i3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i3ActionPerformed
        // TODO add your handling code here:

        String str = String.valueOf(i3.getBackground());
        if (str.equals("java.awt.Color[r=255,g=0,b=0]")) {
        } else if (str.equals("java.awt.Color[r=255,g=255,b=0]")) {
            i3.setBackground(Color.WHITE);
            countingSeats.remove(i3.getText()); // removing that string
//        countingSeats.add(a1.getName()); // adding that string
        } else {
            i3.setBackground(Color.YELLOW);
            //        countingSeats.remove(a1.getName()); // removing that string
            countingSeats.add(i3.getText()); // adding that string
        }

    }//GEN-LAST:event_i3ActionPerformed

    private void f3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f3ActionPerformed
        // TODO add your handling code here:

        String str = String.valueOf(f3.getBackground());
        if (str.equals("java.awt.Color[r=255,g=0,b=0]")) {
        } else if (str.equals("java.awt.Color[r=255,g=255,b=0]")) {
            f3.setBackground(Color.WHITE);
            countingSeats.remove(f3.getText()); // removing that string
//        countingSeats.add(a1.getName()); // adding that string
        } else {
            f3.setBackground(Color.YELLOW);
            //        countingSeats.remove(a1.getName()); // removing that string
            countingSeats.add(f3.getText()); // adding that string
        }

    }//GEN-LAST:event_f3ActionPerformed

    private void g3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g3ActionPerformed
        // TODO add your handling code here:

        String str = String.valueOf(g3.getBackground());
        if (str.equals("java.awt.Color[r=255,g=0,b=0]")) {
        } else if (str.equals("java.awt.Color[r=255,g=255,b=0]")) {
            g3.setBackground(Color.WHITE);
            countingSeats.remove(g3.getText()); // removing that string
//        countingSeats.add(a1.getName()); // adding that string
        } else {
            g3.setBackground(Color.YELLOW);
            //        countingSeats.remove(a1.getName()); // removing that string
            countingSeats.add(g3.getText()); // adding that string
        }

    }//GEN-LAST:event_g3ActionPerformed

    private void h3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h3ActionPerformed
        // TODO add your handling code here:

        String str = String.valueOf(h3.getBackground());
        if (str.equals("java.awt.Color[r=255,g=0,b=0]")) {
        } else if (str.equals("java.awt.Color[r=255,g=255,b=0]")) {
            h3.setBackground(Color.WHITE);
            countingSeats.remove(h3.getText()); // removing that string
//        countingSeats.add(a1.getName()); // adding that string
        } else {
            h3.setBackground(Color.YELLOW);
            //        countingSeats.remove(a1.getName()); // removing that string
            countingSeats.add(h3.getText()); // adding that string
        }

    }//GEN-LAST:event_h3ActionPerformed

    //------------------------------------------- 44444444444444444444444444
    private void a4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a4ActionPerformed
        // TODO add your handling code here:

        String str = String.valueOf(a4.getBackground());
        if (str.equals("java.awt.Color[r=255,g=0,b=0]")) {
        } else if (str.equals("java.awt.Color[r=255,g=255,b=0]")) {
            a4.setBackground(Color.WHITE);
            countingSeats.remove(a4.getText()); // removing that string
//        countingSeats.add(a1.getName()); // adding that string
        } else {
            a4.setBackground(Color.YELLOW);
            //        countingSeats.remove(a1.getName()); // removing that string
            // System.out.println(a4.getText());

            countingSeats.add(a4.getText()); // adding that string
        }

    }//GEN-LAST:event_a4ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:

        String str = String.valueOf(b4.getBackground());
        if (str.equals("java.awt.Color[r=255,g=0,b=0]")) {
        } else if (str.equals("java.awt.Color[r=255,g=255,b=0]")) {
            b4.setBackground(Color.WHITE);
            countingSeats.remove(b4.getText()); // removing that string
//        countingSeats.add(a1.getName()); // adding that string
        } else {
            b4.setBackground(Color.YELLOW);
            //        countingSeats.remove(a1.getName()); // removing that string
            countingSeats.add(b4.getText()); // adding that string
        }

    }//GEN-LAST:event_b4ActionPerformed

    private void c4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c4ActionPerformed
        // TODO add your handling code here:

        String str = String.valueOf(c4.getBackground());
        if (str.equals("java.awt.Color[r=255,g=0,b=0]")) {
        } else if (str.equals("java.awt.Color[r=255,g=255,b=0]")) {
            c4.setBackground(Color.WHITE);
            countingSeats.remove(c4.getText()); // removing that string
//        countingSeats.add(a1.getName()); // adding that string
        } else {
            c4.setBackground(Color.YELLOW);
            //        countingSeats.remove(a1.getName()); // removing that string
            countingSeats.add(c4.getText()); // adding that string
        }

    }//GEN-LAST:event_c4ActionPerformed

    private void d4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d4ActionPerformed
        // TODO add your handling code here:

        String str = String.valueOf(d4.getBackground());
        if (str.equals("java.awt.Color[r=255,g=0,b=0]")) {
        } else if (str.equals("java.awt.Color[r=255,g=255,b=0]")) {
            d4.setBackground(Color.WHITE);
            countingSeats.remove(d4.getText()); // removing that string
//        countingSeats.add(a1.getName()); // adding that string
        } else {
            d4.setBackground(Color.YELLOW);
            //        countingSeats.remove(a1.getName()); // removing that string
            countingSeats.add(d4.getText()); // adding that string
        }

    }//GEN-LAST:event_d4ActionPerformed

    private void h4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h4ActionPerformed
        // TODO add your handling code here:

        String str = String.valueOf(h4.getBackground());
        if (str.equals("java.awt.Color[r=255,g=0,b=0]")) {
        } else if (str.equals("java.awt.Color[r=255,g=255,b=0]")) {
            h4.setBackground(Color.WHITE);
            countingSeats.remove(h4.getText()); // removing that string
//        countingSeats.add(a1.getName()); // adding that string
        } else {
            h4.setBackground(Color.YELLOW);
            //        countingSeats.remove(a1.getName()); // removing that string
            countingSeats.add(h4.getText()); // adding that string
        }

    }//GEN-LAST:event_h4ActionPerformed

    private void g4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g4ActionPerformed
        // TODO add your handling code here:

        String str = String.valueOf(g4.getBackground());

        if (str.equals("java.awt.Color[r=255,g=0,b=0]")) {
        } else if (str.equals("java.awt.Color[r=255,g=255,b=0]")) {
            g4.setBackground(Color.WHITE);
            countingSeats.remove(g4.getText()); // removing that string
//        countingSeats.add(a1.getName()); // adding that string
        } else {
            g4.setBackground(Color.YELLOW);
            //        countingSeats.remove(a1.getName()); // removing that string
            countingSeats.add(g4.getText()); // adding that string
        }

    }//GEN-LAST:event_g4ActionPerformed

    private void f4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f4ActionPerformed
        // TODO add your handling code here:

        String str = String.valueOf(f4.getBackground());
        if (str.equals("java.awt.Color[r=255,g=0,b=0]")) {
        } else if (str.equals("java.awt.Color[r=255,g=255,b=0]")) {
            f4.setBackground(Color.WHITE);
            countingSeats.remove(f4.getText()); // removing that string
//        countingSeats.add(a1.getName()); // adding that string
        } else {
            f4.setBackground(Color.YELLOW);
            //        countingSeats.remove(a1.getName()); // removing that string
            countingSeats.add(f4.getText()); // adding that string
        }

    }//GEN-LAST:event_f4ActionPerformed

    private void e4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_e4ActionPerformed
        // TODO add your handling code here:

        String str = String.valueOf(e4.getBackground());
        if (str.equals("java.awt.Color[r=255,g=0,b=0]")) {
        } else if (str.equals("java.awt.Color[r=255,g=255,b=0]")) {
            e4.setBackground(Color.WHITE);
            countingSeats.remove(e4.getText()); // removing that string
//        countingSeats.add(a1.getName()); // adding that string
        } else {
            e4.setBackground(Color.YELLOW);
            //        countingSeats.remove(a1.getName()); // removing that string
            countingSeats.add(e4.getText()); // adding that string
        }

    }//GEN-LAST:event_e4ActionPerformed


    private void i4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_i4ActionPerformed
        // TODO add your handling code here:

        String str = String.valueOf(i4.getBackground());
        if (str.equals("java.awt.Color[r=255,g=0,b=0]")) {
        } else if (str.equals("java.awt.Color[r=255,g=255,b=0]")) {
            i4.setBackground(Color.WHITE);
            countingSeats.remove(i4.getText()); // removing that string
//        countingSeats.add(a1.getName()); // adding that string
        } else {
            i4.setBackground(Color.YELLOW);
            //        countingSeats.remove(a1.getName()); // removing that string
            countingSeats.add(i4.getText()); // adding that string
        }

    }//GEN-LAST:event_i4ActionPerformed


    //-----------------------End of button Listeners--------------------


    private void backToPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToPreviousActionPerformed
        // TODO add your handling code here:
        SearchResult editSresult = new SearchResult();
        dispose();
        editSresult.show();
    }//GEN-LAST:event_backToPreviousActionPerformed

    String travleFrom, travleto, year, month, day, name;

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
        // TODO add your handling code here:

        ConfirmYourTicket confirmPage = new ConfirmYourTicket();
        int totalSelectedSeats = countingSeats.size();
        confirmPage.getInfo(travleFrom, travleto, coachName, year, month, day, name,totalSelectedSeats,countingSeats,3);
        dispose();
        confirmPage.show();
    }//GEN-LAST:event_nextButtonActionPerformed

    /**
     * @param args the command line arguments
     */


    String coachName;
    BufferedReader readerAC;
    BufferedReader readerNONAC;
//    BufferedReader readerSC;

    {
        try {
            readerAC = new BufferedReader(new FileReader("G:\\Project\\Jabo.com-e-ticket_system\\Jabo.com-e-ticket_system-master\\src\\main\\java\\ALL_Text_Files\\HANIF_Seats\\HANIF_AC.txt"));
            readerNONAC = new BufferedReader(new FileReader("G:\\Project\\Jabo.com-e-ticket_system\\Jabo.com-e-ticket_system-master\\src\\main\\java\\ALL_Text_Files\\HANIF_Seats\\HANIF_nomAC.txt"));
//            readerSC = new BufferedReader(new FileReader("D:\\FINAL PROJECT\\Jabo.com-e-ticket_system-master\\src\\main\\java\\ALL_Text_Files\\GREEN_LINE_seats\\GREEN_LINE_sleeping_coach.txt"));
        } catch (FileNotFoundException e) {
            throw new RuntimeException(e);
        }
    }


    public void getCoachName(String travleFrom, String travleto, String selectedCoach, String year, String month, String day, String name) {
        // tashin

        coachName = name; // string are declared
        this.name = name;
        coachName = selectedCoach; // string are declared
        this.travleFrom = travleFrom;
        this.travleto = travleto;
        this.year = year;
        this.month = month;
        this.day = day;


        if (coachName.toUpperCase().equals("AC")) {
            checkedBookedOrNot(readerAC);
        } else if (coachName.toUpperCase().equals("NON AC")) { // Non CA coach

            checkedBookedOrNot(readerNONAC);

        } else // sleeper coach
        {
//            checkedBookedOrNot(readerSC);
        }
        showCoachName.setText(name);
    }
    // now creat

    void checkedBookedOrNot(BufferedReader reader) {
        try {
            String check; // to get what is position
            int count = 1; // to make button red
            while ((check = reader.readLine()) != null) {
                if (check.toUpperCase().equals("BOOKED")) { // Button will be red
                    // in switch (Char col, int seatNo)
                    if (count <= 4) {
                        //A
                        setColor('a', count);
                    } else if (count <= 4 + 4) {
                        //B
                        setColor('b', count);
                    } else if (count <= 4 + 4 + 4) {
                        //C
                        setColor('c', count);
                    } else if (count <= 4 + 4 + 4 + 4) {
                        //D
                        setColor('d', count);
                    } else if (count <= 4 + 4 + 4 + 4 + 4) {
                        //e
                        setColor('e', count);
                    } else if (count <= 4 + 4 + 4 + 4 + 4 + 4) { // 6 ta 4
                        //f
                        setColor('f', count);
                    } else if (count <= 4 * 7) {
                        setColor('g', count);
                    } else if (count <= 4 * 8) {
                        setColor('h', count);
                    } else if (count <= 4 * 9) {
                        setColor('i', count);
                    }
                    count++;
                    // above all are done and looks fine
                } else {
                    count++;
                }
            } // end of while Loop
            reader.close();


        } catch (FileNotFoundException e) {
            throw new RuntimeException(e);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    void setColor(char column, int seatNo) {
        int col = 0;
        int mainSeatNo;
        switch (column) {
            case 'a':
                col = 0;
                mainSeatNo = seatNo - col;
                if (mainSeatNo == 1) a1.setBackground(Color.RED);
                if (mainSeatNo == 2) a2.setBackground(Color.RED);
                if (mainSeatNo == 3) a3.setBackground(Color.RED);
                if (mainSeatNo == 4) a4.setBackground(Color.RED);
                break;
            case 'b':
                col = 4;
                mainSeatNo = seatNo - col;
                if (mainSeatNo == 1) b1.setBackground(Color.RED);
                if (mainSeatNo == 2) b2.setBackground(Color.RED);
                if (mainSeatNo == 3) b3.setBackground(Color.RED);
                if (mainSeatNo == 4) b4.setBackground(Color.RED);
                break;
            case 'c':
                col = 8;
                mainSeatNo = seatNo - col;
                if (mainSeatNo == 1) c1.setBackground(Color.RED);
                if (mainSeatNo == 2) c2.setBackground(Color.RED);
                if (mainSeatNo == 3) c3.setBackground(Color.RED);
                if (mainSeatNo == 4) c4.setBackground(Color.RED);
                break;
            case 'd':
                col = 12;
                mainSeatNo = seatNo - col;
                if (mainSeatNo == 1) d1.setBackground(Color.RED);
                if (mainSeatNo == 2) d2.setBackground(Color.RED);
                if (mainSeatNo == 3) d3.setBackground(Color.RED);
                if (mainSeatNo == 4) d4.setBackground(Color.RED);
                break;
            case 'e':
                col = 16;
                mainSeatNo = seatNo - col;
                if (mainSeatNo == 1) e1.setBackground(Color.RED);
                if (mainSeatNo == 2) e2.setBackground(Color.RED);
                if (mainSeatNo == 3) e3.setBackground(Color.RED);
                if (mainSeatNo == 4) e4.setBackground(Color.RED);
                break;
            case 'f':
                col = 20;
                mainSeatNo = seatNo - col;
                if (mainSeatNo == 1) f1.setBackground(Color.RED);
                if (mainSeatNo == 2) f2.setBackground(Color.RED);
                if (mainSeatNo == 3) f3.setBackground(Color.RED);
                if (mainSeatNo == 4) f4.setBackground(Color.RED);
                break;
            case 'g':
                col = 4 * 6;
                mainSeatNo = seatNo - col;
                if (mainSeatNo == 1) g1.setBackground(Color.RED);
                if (mainSeatNo == 2) g2.setBackground(Color.RED);
                if (mainSeatNo == 3) g3.setBackground(Color.RED);
                if (mainSeatNo == 4) g4.setBackground(Color.RED);
                break;
            case 'h':
                col = 4 * 7;
                mainSeatNo = seatNo - col;
                if (mainSeatNo == 1) h1.setBackground(Color.RED);
                if (mainSeatNo == 2) h2.setBackground(Color.RED);
                if (mainSeatNo == 3) h3.setBackground(Color.RED);
                if (mainSeatNo == 4) h4.setBackground(Color.RED);
                break;
            case 'i':
                col = 4 * 8;
                mainSeatNo = seatNo - col;
                if (mainSeatNo == 1) i1.setBackground(Color.RED);
                if (mainSeatNo == 2) i2.setBackground(Color.RED);
                if (mainSeatNo == 3) i3.setBackground(Color.RED);
                if (mainSeatNo == 4) i4.setBackground(Color.RED);
                break;
            // above all are fine
        }
    }


    //___________________________________________________________________________________ UPTO HERE


    //_____________________++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hanif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hanif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hanif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hanif.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hanif().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton a1;
    private javax.swing.JButton a2;
    private javax.swing.JButton a3;
    private javax.swing.JButton a4;
    private javax.swing.JLabel applicationName1;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton backToPrevious;
    private javax.swing.JButton c1;
    private javax.swing.JButton c2;
    private javax.swing.JButton c3;
    private javax.swing.JButton c4;
    private javax.swing.JButton d1;
    private javax.swing.JButton d2;
    private javax.swing.JButton d3;
    private javax.swing.JButton d4;
    private javax.swing.JButton e1;
    private javax.swing.JButton e2;
    private javax.swing.JButton e3;
    private javax.swing.JButton e4;
    private javax.swing.JButton f1;
    private javax.swing.JButton f2;
    private javax.swing.JButton f3;
    private javax.swing.JButton f4;
    private javax.swing.JButton g1;
    private javax.swing.JButton g2;
    private javax.swing.JButton g3;
    private javax.swing.JButton g4;
    private javax.swing.JButton h1;
    private javax.swing.JButton h2;
    private javax.swing.JButton h3;
    private javax.swing.JButton h4;
    private javax.swing.JButton i1;
    private javax.swing.JButton i2;
    private javax.swing.JButton i3;
    private javax.swing.JButton i4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JButton nextButton;
    private javax.swing.JLabel showCoachName;
    // End of variables declaration//GEN-END:variables
}
