//package com.mycompany.online_eticket_system_jabo.ForntPages;
//
//import AfterLogInPage.TripDetails;
//
//import javax.swing.*;
//import java.io.BufferedReader;
//import java.io.FileReader;
//import java.io.IOException;
//
///**
// * @author Tashin Parvez
// */
//public class LogInForm extends javax.swing.JFrame {
//
//    /**
//     * Creates new form LogInForm
//     */
//
//    public LogInForm() {
//        //   setLocationRelativeTo(null);
//        initComponents();
//    }
//
//
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
//    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
//    private void initComponents() {
//
//        jPanel3 = new javax.swing.JPanel();
//        jLabel2 = new javax.swing.JLabel();
//        jLabel3 = new javax.swing.JLabel();
//        jPanel1 = new javax.swing.JPanel();
//        applicationName = new javax.swing.JLabel();
//        jLabel1 = new javax.swing.JLabel();
//        jPanel2 = new javax.swing.JPanel();
//        logInemailOrHandlle = new javax.swing.JTextField();
//        logInButton = new javax.swing.JButton();
//        accountCreatButton = new javax.swing.JButton();
//        PasswordField = new javax.swing.JPasswordField();
//        jLabel4 = new javax.swing.JLabel();
//        jLabel5 = new javax.swing.JLabel();
//
//        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
//        jPanel3.setLayout(jPanel3Layout);
//        jPanel3Layout.setHorizontalGroup(
//                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGap(0, 100, Short.MAX_VALUE)
//        );
//        jPanel3Layout.setVerticalGroup(
//                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGap(0, 100, Short.MAX_VALUE)
//        );
//
//        jLabel2.setText("jLabel2");
//
//        jLabel3.setText("jLabel3");
//
//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//
//        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
//
//        applicationName.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
//        applicationName.setText("JABO");
//
//        jLabel1.setText("Choose Your Comfort");
//
//        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
//
//        logInButton.setBackground(new java.awt.Color(102, 102, 255));
//        logInButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
//        logInButton.setText("LogIn");
//        logInButton.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                logInButtonActionPerformed(evt);
//            }
//        });
//
//        accountCreatButton.setBackground(new java.awt.Color(51, 0, 153));
//        accountCreatButton.setForeground(new java.awt.Color(255, 255, 204));
//        accountCreatButton.setText("Creat New Account");
//        accountCreatButton.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                accountCreatButtonActionPerformed(evt);
//            }
//        });
//
//        jLabel4.setText("Enter email or handle");
//
//        jLabel5.setText("Password");
//
//        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
//        jPanel2.setLayout(jPanel2Layout);
//        jPanel2Layout.setHorizontalGroup(
//                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(jPanel2Layout.createSequentialGroup()
//                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                        .addGroup(jPanel2Layout.createSequentialGroup()
//                                                .addGap(52, 52, 52)
//                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                        .addComponent(logInemailOrHandlle, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                        .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                                        .addGroup(jPanel2Layout.createSequentialGroup()
//                                                .addGap(110, 110, 110)
//                                                .addComponent(logInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                                .addContainerGap(54, Short.MAX_VALUE))
//                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
//                                .addGap(0, 0, Short.MAX_VALUE)
//                                .addComponent(accountCreatButton)
//                                .addGap(119, 119, 119))
//        );
//        jPanel2Layout.setVerticalGroup(
//                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
//                                .addContainerGap(25, Short.MAX_VALUE)
//                                .addComponent(jLabel4)
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                .addComponent(logInemailOrHandlle, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                .addComponent(jLabel5)
//                                .addGap(8, 8, 8)
//                                .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addGap(22, 22, 22)
//                                .addComponent(logInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addGap(18, 18, 18)
//                                .addComponent(accountCreatButton)
//                                .addGap(37, 37, 37))
//        );
//
//        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
//        jPanel1.setLayout(jPanel1Layout);
//        jPanel1Layout.setHorizontalGroup(
//                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(jPanel1Layout.createSequentialGroup()
//                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                        .addGroup(jPanel1Layout.createSequentialGroup()
//                                                .addGap(174, 174, 174)
//                                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                        .addGroup(jPanel1Layout.createSequentialGroup()
//                                                .addGap(296, 296, 296)
//                                                .addComponent(jLabel1))
//                                        .addGroup(jPanel1Layout.createSequentialGroup()
//                                                .addGap(326, 326, 326)
//                                                .addComponent(applicationName)))
//                                .addContainerGap(175, Short.MAX_VALUE))
//        );
//        jPanel1Layout.setVerticalGroup(
//                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(jPanel1Layout.createSequentialGroup()
//                                .addGap(76, 76, 76)
//                                .addComponent(applicationName)
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                                .addComponent(jLabel1)
//                                .addGap(18, 18, 18)
//                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addContainerGap(72, Short.MAX_VALUE))
//        );
//
//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//        );
//        layout.setVerticalGroup(
//                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//        );
//
//        pack();
//        setLocationRelativeTo(null);
//    }// </editor-fold>//GEN-END:initComponents
//
//    private void accountCreatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountCreatButtonActionPerformed
//        // TODO add your handling code here:
//        AccountCreatPage newAccount = new AccountCreatPage();
//        dispose();
//        newAccount.show();
//    }//GEN-LAST:event_accountCreatButtonActionPerformed
//
////    private void logInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInButtonActionPerformed
////        // TODO add your handling code here:
////
////        //----------------------- login validation codes_________________________________________
////
////        try {
////            String givenHandleOrMail = logInemailOrHandlle.getText();
////            String givenPassword = PasswordField.getText();
////
////            if (givenHandleOrMail.equals("") || givenPassword.equals("")) {
////                JOptionPane.showMessageDialog(this, "Enter User Name and Password");
////            } else {
////                BufferedReader read = new BufferedReader(new FileReader("G:\\Project\\Jabo.com-e-ticket_system\\Jabo.com-e-ticket_system-master\\src\\main\\java\\ALL_Text_Files\\UserLogInInformation.txt"));
////                String str;
////                int flag = 0;
////                while ((str = read.readLine()) != null) {
////                    String[] userInfo = str.split(",");
////                    if (userInfo.length >= 2) {
////                        if (userInfo[0].equals(givenHandleOrMail) || userInfo[1].equals(givenHandleOrMail)) {
////                            if (userInfo.length >= 3 && userInfo[2].equals(givenPassword)) {
////                                TripDetails userLogin = new TripDetails();
////                                flag = 1;
////                                dispose();
////                                userLogin.getInfo(givenHandleOrMail);
////                                userLogin.show();
////                                break;
////                            }
////                        }
////                    }
////                }
////
////
////                if (flag == 0) {
////                    JOptionPane.showMessageDialog(this, "Wrong Password");
////                }
////
////                read.close();
////            }
////        } catch (IOException e) {
////            throw new RuntimeException(e);
////        }
////
////
////    }
////
//private void logInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInButtonActionPerformed
//    try {
//        String givenHandleOrMail = logInemailOrHandlle.getText().trim(); // Trim any leading or trailing spaces
//        String givenPassword = new String(PasswordField.getPassword());
//
//        if (givenHandleOrMail.isEmpty() || givenPassword.isEmpty()) {
//            JOptionPane.showMessageDialog(this, "Enter User Name and Password");
//        } else {
//            String filePath = "G:\\Project\\Jabo.com-e-ticket_system\\Jabo.com-e-ticket_system-master\\src\\main\\java\\ALL_Text_Files\\UserLogInInformation.txt";
//            try (BufferedReader read = new BufferedReader(new FileReader(filePath))) {
//                String line;
//                boolean userFound = false;
//                while ((line = read.readLine()) != null) {
//                    System.out.println("Line read from file: " + line); // Debug statement
//
//                    String[] userInfo = line.split(",");
//                    // Check if email/handle matches, ignoring case
//                    if (userInfo.length >= 3 && (userInfo[0].trim().equalsIgnoreCase(givenHandleOrMail) || userInfo[1].trim().equalsIgnoreCase(givenHandleOrMail)) && userInfo[2].equals(givenPassword)) {
//                        userFound = true;
//                        System.out.println("User found: " + line); // Debug statement
//
//
//                        TripDetails userLogin = new TripDetails();
//                        dispose();
//                        userLogin.getInfo(givenHandleOrMail);
//                        userLogin.setVisible(true);
//                        break;
//                    }
//                }
//
//                if (!userFound) {
//                    JOptionPane.showMessageDialog(this, "Wrong Password or User not found");
//                }
//            } catch (IOException e) {
//                e.printStackTrace();
//                JOptionPane.showMessageDialog(this, "Error accessing user information");
//            }
//        }
//    } catch (Exception e) {
//        e.printStackTrace();
//        JOptionPane.showMessageDialog(this, "An error occurred during login");
//    }
//}
//
//// GEN-LAST:event_logInButtonActionPerformed
//
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(LogInForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(LogInForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(LogInForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(LogInForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new LogInForm().setVisible(true);
//            }
//        });
//    }
//
//    // Variables declaration - do not modify//GEN-BEGIN:variables
//    private javax.swing.JPasswordField PasswordField;
//    private javax.swing.JButton accountCreatButton;
//    private javax.swing.JLabel applicationName;
//    private javax.swing.JLabel jLabel1;
//    private javax.swing.JLabel jLabel2;
//    private javax.swing.JLabel jLabel3;
//    private javax.swing.JLabel jLabel4;
//    private javax.swing.JLabel jLabel5;
//    private javax.swing.JPanel jPanel1;
//    private javax.swing.JPanel jPanel2;
//    private javax.swing.JPanel jPanel3;
//    private javax.swing.JButton logInButton;
//    private javax.swing.JTextField logInemailOrHandlle;
//    // End of variables declaration//GEN-END:variables
//}


package com.mycompany.online_eticket_system_jabo.ForntPages;

import AfterLogInPage.TripDetails;

import javax.swing.*;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;

public class LogInForm extends javax.swing.JFrame {

    public LogInForm() {
        initComponents();
    }

    @SuppressWarnings("unchecked")
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        applicationName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        logInemailOrHandlle = new javax.swing.JTextField();
        logInButton = new javax.swing.JButton();
        accountCreatButton = new javax.swing.JButton();
        PasswordField = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        applicationName.setFont(new java.awt.Font("Segoe UI Black", 1, 18));
        applicationName.setText("JABO");

        jLabel1.setText("Choose Your Comfort");

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        logInButton.setBackground(new java.awt.Color(102, 102, 255));
        logInButton.setFont(new java.awt.Font("Segoe UI", 1, 12));
        logInButton.setText("LogIn");
        logInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInButtonActionPerformed(evt);
            }
        });

        accountCreatButton.setBackground(new java.awt.Color(51, 0, 153));
        accountCreatButton.setForeground(new java.awt.Color(255, 255, 204));
        accountCreatButton.setText("Create New Account");
        accountCreatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountCreatButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Enter email or handle");

        jLabel5.setText("Password");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(52, 52, 52)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(logInemailOrHandlle, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(110, 110, 110)
                                                .addComponent(logInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(54, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(accountCreatButton)
                                .addGap(119, 119, 119))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap(25, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(logInemailOrHandlle, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addGap(8, 8, 8)
                                .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(logInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(accountCreatButton)
                                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(174, 174, 174)
                                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(296, 296, 296)
                                                .addComponent(jLabel1))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(326, 326, 326)
                                                .addComponent(applicationName)))
                                .addContainerGap(175, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(applicationName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }

    private void accountCreatButtonActionPerformed(java.awt.event.ActionEvent evt) {
        AccountCreatPage newAccount = new AccountCreatPage();
        dispose();
        newAccount.show();
    }

    private void logInButtonActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            String givenHandleOrMail = logInemailOrHandlle.getText();
            String givenPassword = new String(PasswordField.getPassword());

            if (givenHandleOrMail.isEmpty() || givenPassword.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Enter User Name and Password");
            } else {
                String filePath = "G:\\Project\\Jabo.com-e-ticket_system\\Jabo.com-e-ticket_system-master\\src\\main\\java\\ALL_Text_Files\\UserLogInInformation.txt";
                try (BufferedReader read = new BufferedReader(new FileReader(filePath))) {
                    String line;
                    boolean userFound = false;
                    while ((line = read.readLine()) != null) {
                        String[] userInfo = line.split(",");
                        if (userInfo.length >= 3 && (userInfo[2].equals(givenHandleOrMail) || userInfo[3].equals(givenHandleOrMail)) && userInfo[4].equals(givenPassword)) {
                            userFound = true;
                            TripDetails userLogin = new TripDetails();
                            dispose();
                            userLogin.getInfo(userInfo[2]); // Passing handle/email to TripDetails
                            userLogin.setVisible(true);
                            break;
                        }
                    }

                    if (!userFound) {
                        JOptionPane.showMessageDialog(this, "Wrong Password or User not found");
                    }
                } catch (IOException e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(this, "Error accessing user information");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "An error occurred during login");
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogInForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogInForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogInForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogInForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogInForm().setVisible(true);
            }
        });
    }

    private javax.swing.JButton accountCreatButton;
    private javax.swing.JLabel applicationName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JButton logInButton;
    private javax.swing.JTextField logInemailOrHandlle;
}
