/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AfterLogInPage;

import Available_Busses.ENA_Paribahan;
import Available_Busses.GreenLine;
import Available_Busses.Hanif;
import Available_Busses.Shyamoli_Paribahan;

/**
 * @author Tashin Parvez
 */
public class SearchResult extends javax.swing.JFrame {

    public String travleFrom, travleto, selectedCoach, year, month, day;


    /**
     * Creates new form SearchResult
     */

    public SearchResult() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        applicationName1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        backToPreviousPageButton = new javax.swing.JButton();
        EnaCart = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        enaSeats = new javax.swing.JLabel();
        enaSeatCost = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        optionOne_Ena = new javax.swing.JButton();
        OneCart1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        glSeats = new javax.swing.JLabel();
        glSeatCost = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        optionThree_Green = new javax.swing.JButton();
        hanifCart = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        hanifSeats = new javax.swing.JLabel();
        hanifSeatCost = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        optionTwo_Hanif = new javax.swing.JButton();
        shymoliCart = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        shySeats = new javax.swing.JLabel();
        shymoliSeatCost = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        optionFour_Shyamoli = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        locationBar = new javax.swing.JLabel();
        dateAndTimeBar = new javax.swing.JLabel();
        CoachInfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        applicationName1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        applicationName1.setText("JABO");

        backToPreviousPageButton.setBackground(new java.awt.Color(0, 51, 51));
        backToPreviousPageButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        backToPreviousPageButton.setForeground(new java.awt.Color(204, 255, 204));
        backToPreviousPageButton.setText("Back to Previous Page");
        backToPreviousPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToPreviousPageButtonActionPerformed(evt);
            }
        });

        EnaCart.setBackground(new java.awt.Color(204, 255, 204));
        EnaCart.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ena");

        enaSeats.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        enaSeats.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        enaSeats.setText("Available Seats: 20");

        enaSeatCost.setFont(new java.awt.Font("Sylfaen", 1, 16)); // NOI18N
        enaSeatCost.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        enaSeatCost.setText("1200 TK");

        optionOne_Ena.setBackground(new java.awt.Color(0, 153, 153));
        optionOne_Ena.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        optionOne_Ena.setText("Book Now");
        optionOne_Ena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionOne_EnaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EnaCartLayout = new javax.swing.GroupLayout(EnaCart);
        EnaCart.setLayout(EnaCartLayout);
        EnaCartLayout.setHorizontalGroup(
            EnaCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EnaCartLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EnaCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enaSeatCost, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(enaSeats, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(jSeparator1))
                .addContainerGap())
            .addGroup(EnaCartLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(optionOne_Ena, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EnaCartLayout.setVerticalGroup(
            EnaCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EnaCartLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enaSeatCost, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(enaSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(optionOne_Ena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        OneCart1.setBackground(new java.awt.Color(0, 255, 204));
        OneCart1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setBackground(new java.awt.Color(0, 255, 204));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Green Line");

        glSeats.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        glSeats.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        glSeats.setText("Available Seats: 20");

        glSeatCost.setFont(new java.awt.Font("Sylfaen", 1, 16)); // NOI18N
        glSeatCost.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        glSeatCost.setText("1200 TK");

        optionThree_Green.setBackground(new java.awt.Color(153, 255, 204));
        optionThree_Green.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        optionThree_Green.setText("Book Now");
        optionThree_Green.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionThree_GreenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OneCart1Layout = new javax.swing.GroupLayout(OneCart1);
        OneCart1.setLayout(OneCart1Layout);
        OneCart1Layout.setHorizontalGroup(
            OneCart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OneCart1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OneCart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(glSeatCost, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(glSeats, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(jSeparator2))
                .addContainerGap())
            .addGroup(OneCart1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(optionThree_Green, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        OneCart1Layout.setVerticalGroup(
            OneCart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OneCart1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(glSeatCost, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(glSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(optionThree_Green, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        hanifCart.setBackground(new java.awt.Color(204, 204, 255));
        hanifCart.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Hanif");

        hanifSeats.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        hanifSeats.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hanifSeats.setText("Available Seats: 20");

        hanifSeatCost.setFont(new java.awt.Font("Sylfaen", 1, 16)); // NOI18N
        hanifSeatCost.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hanifSeatCost.setText("1200 TK");

        optionTwo_Hanif.setBackground(new java.awt.Color(0, 204, 204));
        optionTwo_Hanif.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        optionTwo_Hanif.setText("Book Now");
        optionTwo_Hanif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionTwo_HanifActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout hanifCartLayout = new javax.swing.GroupLayout(hanifCart);
        hanifCart.setLayout(hanifCartLayout);
        hanifCartLayout.setHorizontalGroup(
            hanifCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hanifCartLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(hanifCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hanifSeatCost, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hanifSeats, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(jSeparator3))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hanifCartLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(optionTwo_Hanif)
                .addGap(31, 31, 31))
        );
        hanifCartLayout.setVerticalGroup(
            hanifCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hanifCartLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hanifSeatCost, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(hanifSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(optionTwo_Hanif, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        shymoliCart.setBackground(new java.awt.Color(0, 153, 153));
        shymoliCart.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Shyamoli");

        shySeats.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        shySeats.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        shySeats.setText("Available Seats: 20");

        shymoliSeatCost.setFont(new java.awt.Font("Sylfaen", 1, 16)); // NOI18N
        shymoliSeatCost.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        shymoliSeatCost.setText("1200 TK");

        optionFour_Shyamoli.setBackground(new java.awt.Color(204, 204, 255));
        optionFour_Shyamoli.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        optionFour_Shyamoli.setText("Book Now");
        optionFour_Shyamoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionFour_ShyamoliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout shymoliCartLayout = new javax.swing.GroupLayout(shymoliCart);
        shymoliCart.setLayout(shymoliCartLayout);
        shymoliCartLayout.setHorizontalGroup(
            shymoliCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shymoliCartLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(shymoliCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(shymoliSeatCost, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(shySeats, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(jSeparator4))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, shymoliCartLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(optionFour_Shyamoli, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        shymoliCartLayout.setVerticalGroup(
            shymoliCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, shymoliCartLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(shymoliSeatCost, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(shySeats, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(optionFour_Shyamoli, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(backToPreviousPageButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(EnaCart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(OneCart1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hanifCart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(shymoliCart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OneCart1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EnaCart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hanifCart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shymoliCart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(backToPreviousPageButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 255, 204));

        locationBar.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        locationBar.setText("DHAKA - SHYLET");

        dateAndTimeBar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        dateAndTimeBar.setText("30 December, 2022");

        CoachInfo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CoachInfo.setText("Coach: AC");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(locationBar, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(CoachInfo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dateAndTimeBar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(locationBar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateAndTimeBar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CoachInfo)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(applicationName1)
                        .addGap(31, 31, 31)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(applicationName1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backToPreviousPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToPreviousPageButtonActionPerformed
        // TODO add your handling code here:
        // codes will be here


        //--------- bellow all area ok
        TripDetails editTripDetails = new TripDetails();
        editTripDetails.gettingTheTravelInfo(travleFrom, travleto, selectedCoach, year, month, day); // passing the infos those are already diven
        dispose();
        editTripDetails.show();
    }//GEN-LAST:event_backToPreviousPageButtonActionPerformed

    private void optionOne_EnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionOne_EnaActionPerformed
        // TODO add your handling code here:
        // tashin

        ENA_Paribahan cutEnaTicket = new ENA_Paribahan();
        cutEnaTicket.getCoachName(travleFrom, travleto, selectedCoach, year, month, day, name); // passing the coachName to the Bus Seat window

        dispose();
        cutEnaTicket.show();
    }//GEN-LAST:event_optionOne_EnaActionPerformed

    private void optionTwo_HanifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionTwo_HanifActionPerformed
        // TODO add your handling code here:
        Hanif cutHanifTicket = new Hanif();

        cutHanifTicket.getCoachName(travleFrom, travleto, selectedCoach, year, month, day, name); // passing the coachName to the Bus Seat window
        dispose();
        cutHanifTicket.show();
    }//GEN-LAST:event_optionTwo_HanifActionPerformed

    private void optionThree_GreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionThree_GreenActionPerformed
        // TODO add your handling code here:
        GreenLine cutGreenLineTicket = new GreenLine();

        cutGreenLineTicket.getCoachName(travleFrom, travleto, selectedCoach, year, month, day, name);

        dispose();
        cutGreenLineTicket.show();
    }//GEN-LAST:event_optionThree_GreenActionPerformed

    private void optionFour_ShyamoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_optionFour_ShyamoliActionPerformed
        // TODO add your handling code here:
        Shyamoli_Paribahan cutShyamoliTicket = new Shyamoli_Paribahan();

        cutShyamoliTicket.getCoachName(travleFrom, travleto, selectedCoach, year, month, day, name);
        dispose();
        cutShyamoliTicket.show();
    }//GEN-LAST:event_optionFour_ShyamoliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchResult().setVisible(true);
            }
        });
    }

    //----------------MY Function
    String name;

    public void takingTripDetails(String travleFrom, String travleto, String selectedCoach, String year, String month, String day, String name) {
        //  travleFrom,travleto,selectedCoach,year,month,day
        this.name = name;
        forthePreviousButtoncodes(travleFrom, travleto, selectedCoach, year, month, day);
        locationBar.setText(travleFrom + " - " + travleto);
        dateAndTimeBar.setText(day + " " + month + ", " + year);
        CoachInfo.setText("Coach: " + " " + selectedCoach);

        // selectedCoach
        if (selectedCoach.toUpperCase().equals("AC")) {
            enaSeatCost.setText("1280 TK");
            glSeatCost.setText("1300 TK");
            hanifSeatCost.setText("1200 TK");
            shymoliSeatCost.setText("1080 TK");

            //Available Seats: 20
            enaSeats.setText("Available Seats: 10");
            glSeats.setText("Available Seats: 20");
            hanifSeats.setText("Available Seats: 18");
            shySeats.setText("Available Seats: 08");

        } else if (selectedCoach.toUpperCase().equals("NON AC")) {
            enaSeatCost.setText("880 TK");
            glSeatCost.setText("1000 TK");
            hanifSeatCost.setText("800 TK");
            shymoliSeatCost.setText("770 TK");

            // seats
            enaSeats.setText("Available Seats: 25");
            glSeats.setText("Available Seats: 30");
            hanifSeats.setText("Available Seats: 22");
            shySeats.setText("Available Seats: 20");
        } else { // sleeper coach

            enaSeatCost.setText("2800 TK");
            glSeatCost.setText("3200 TK");

            //seats
            enaSeats.setText("Available Seats: 30");
            glSeats.setText("Available Seats: 20");


            hanifCart.setVisible(false);
            shymoliCart.setVisible(false);
        }


    }

    void forthePreviousButtoncodes(String travleFro, String travlet, String selectedCoac, String yea, String mont, String da) {
        this.travleFrom = travleFro;
        this.travleto = travlet;
        this.selectedCoach = selectedCoac;
        this.year = yea;
        this.month = mont;
        this.day = da;
    }

    //--------------------------
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CoachInfo;
    private javax.swing.JPanel EnaCart;
    private javax.swing.JPanel OneCart1;
    private javax.swing.JLabel applicationName1;
    private javax.swing.JButton backToPreviousPageButton;
    private javax.swing.JLabel dateAndTimeBar;
    private javax.swing.JLabel enaSeatCost;
    private javax.swing.JLabel enaSeats;
    private javax.swing.JLabel glSeatCost;
    private javax.swing.JLabel glSeats;
    private javax.swing.JPanel hanifCart;
    private javax.swing.JLabel hanifSeatCost;
    private javax.swing.JLabel hanifSeats;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel locationBar;
    private javax.swing.JButton optionFour_Shyamoli;
    private javax.swing.JButton optionOne_Ena;
    private javax.swing.JButton optionThree_Green;
    private javax.swing.JButton optionTwo_Hanif;
    private javax.swing.JLabel shySeats;
    private javax.swing.JPanel shymoliCart;
    private javax.swing.JLabel shymoliSeatCost;
    // End of variables declaration//GEN-END:variables
}
// 
